# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dalzone
email: dalzony at gmail.com
description: > # this means to ignore newlines until "baseurl:"
  perl -> objective-c -> clojure
  developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dalzony.github.io/" # the base hostname & protocol for your site
twitter_username: dalzony
github_username:  dalzony

# Build settings
# markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:month/:title

future: true

# disqus
disqus: dalzone-blog
